name: Build Arch Package

on:
  push:
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm \
            base-devel git meson ninja glib2 nss pixman libgusb glib2-devel \
            gobject-introspection valgrind gtk-doc libgudev

      - name: Build package
        run: |
          useradd -m builder
          chown -R builder:builder "$GITHUB_WORKSPACE"

          su builder -c 'makepkg -s --noconfirm'

      - name: Create Release and upload package
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.pkg.tar.zst
          generate_release_notes: true
